repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=500"]
        exclude: ^examples/integrations/rasa/rasa_project/poetry\.lock$
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-json
        files: \.json$

  - repo: https://github.com/lucas-c/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: insert-license
        files: \.py$
        args:
          - --license-filepath=.license-header
          - --comment-style=#

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
